package com.stockapp.domain.stock;

public enum StockMasterStatusEventType {
    MASTER_FIRST_SEEN,
    MASTER_MISSING_OBSERVED,
    MASTER_REAPPEARED,
    STOCK_NAME_CHANGED,
    MARKET_CHANGED,
    STANDARD_CODE_CHANGED,
    INSTRUMENT_TYPE_CHANGED,
    SUSPENDED_CHANGED,
    LIQUIDATION_TRADING_CHANGED,
    MANAGED_ISSUE_CHANGED,
    SPAC_CHANGED
}
